spring:
  application:
    name: dashboard


  data:
    mongodb:
      uri: YOUR_MONGODB_ATLAS_URI
      auto-index-creation: true
  main:
    allow-circular-references: true



server:
  port: 8080
